### ISSUE TITLE
Field of view changes depending on aspect ratio

### ISSUE THREAD

**Issue by JNishimura** [bchoi12/birdtown#1]
This game is awesome! I play on ultrawide and I'm not able to see as much of the game when my window is at my monitor's 21:9 aspect ratio vs when I adjust the window to something closer to 16:9. It seems like lots of the vertical field of view is lost 😭. Maybe it's possible to add an option to not have the game window take up the full browser window's width?

Ultrawide: 
![Screenshot 2024-03-04 171805](https://github.com/bchoi12/birdtown/assets/20128472/58189b08-9325-4d08-9235-e387e47cc2c5)

Adjusted window:
![Screenshot 2024-03-04 171557](https://github.com/bchoi12/birdtown/assets/20128472/c556fb4d-ba25-4a1e-a9bb-9fe78eedb05d)

**Comment by bchoi12** [comment]
Thanks for the detailed report. I didn't take into account ultra-wide when determining the FOV, which is fixed horizontally. The viewport is also always stretched to fill 100% of the width.

I can try playing around with CSS to see if we can instead support a small range of aspect ratios and cap how much the viewport extends both horizontally and vertically.

**Comment by bchoi12** [comment]
I added some support to cap the aspect ratio roughly between 1.6:1 and 2.2:1. On ultra-wide the vertical FOV will still be more restricted, but there is a minimum now.

The game will not stretch beyond the aspect ratio range

![bugfix](https://github.com/bchoi12/birdtown/assets/6346923/803f9093-a102-4f90-ac3c-ce60001fcd1f)

Enjoy your ultra-wide gaming
